import numpy as np

A=np.ones((3))
B=A+A
print(A,B)
C=np.vstack((A,B))
print(np.vstack((A,B)))
print(np.shape(C))
print(A.shape)
D=np.hstack((A,B))
print(D.shape)
print(np.hstack((A,B)))
print(A[np.newaxis,:])
print(A.reshape(3,1))
print(A,B)
C=np.concatenate((A,B,A))
print(C)
D=np.concatenate((A,A,A,B),axis=0)
print(D)
A=A.reshape(-1,1)
B=B.reshape(-1,1)
print(A,"\n",B)
E=np.concatenate((A,B,B,A),axis=1)
print(E)